'use client'
import {  ClerkProvider} from '@clerk/nextjs'
import { Roboto, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./_components/footer";
import Header from "./_components/header";
import DismissibleDiv from "./_components/announcy";
import {CartContext} from './_context/CartContext'
import { useState } from 'react';
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
});
/*
export const metadata = {
  title: " ecommerce App",
  description: "Generated by create next app",
};
*/
export default function RootLayout({ children }) {
  const [cart,setCart] = useState([])
  return (
    <ClerkProvider>
<CartContext.Provider value={{ cart, setCart }}>
<html lang="en">
      <body
className={`${roboto.variable} ${robotoMono.variable}`}      >
        <DismissibleDiv/>
        <Header/>
                {children}
        <Footer/>
      </body>
    </html>
    </CartContext.Provider>
    </ClerkProvider>
  );
}
